name: Demo2-Job Level Env
on: push

jobs:
  run-app:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: job-level-variable

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t env-demo .

      - name: Run Container
        run: docker run -e ENV_NAME=$ENV_NAME env-demo